###  Todos los tickets
GET http://localhost:1234/tickets

### Tickets por prioridad
GET http://localhost:1234/tickets?priority=low

### Tickets por estado
GET http://localhost:1234/tickets?status=open

### Tickets por prioridad y estado
GET http://localhost:1234/tickets?priority=low&status=open

### Ticket por id
GET http://localhost:1234/tickets/23bf052e-e4bf-463f-a763-0a237194a771

### Crear ticket
POST http://localhost:1234/tickets
Content-Type: application/json

{
    "title": "Ticket de prueba",
    "description": "Descripción de prueba",
    "priority": "high",
    "status": "open",
    "tags": ["test"]
}

### Actualizar ticket
PATCH http://localhost:1234/tickets/23bf052e-e4bf-463f-a763-0a237194a771
Content-Type: application/json

{
    "status": "closed"
}

### Eliminar ticket
DELETE http://localhost:1234/tickets/23bf052e-e4bf-463f-a763-0a237194a771
