DROP DATABASE IF EXISTS gadgets;
CREATE DATABASE gadgets;
USE gadgets;

CREATE TABLE users (
  id CHAR(36) PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE users 
  MODIFY password VARCHAR(100) NULL, -- NULL para usuarios de OAuth2
  ADD COLUMN provider VARCHAR(20) DEFAULT 'local', -- 'local', 'google'
  ADD COLUMN provider_id VARCHAR(100) UNIQUE NULL; -- El ID que te da Google

CREATE TABLE brand (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE gadget (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  price DECIMAL(10, 2) NOT NULL,
  stock INT NOT NULL DEFAULT 0,
  brand_id INT,
  FOREIGN KEY (brand_id) REFERENCES brand(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE category (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE gadget_categories (
  gadget_id CHAR(36),
  category_id INT,
  PRIMARY KEY(gadget_id, category_id),
  FOREIGN KEY (gadget_id) REFERENCES gadget(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE ON UPDATE CASCADE
);
